name: Emacs package CI

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    name: byte-compile on Emacs 29.3
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the source code
      - uses: actions/checkout@v4

      # Step 2: Install dependencies for building Emacs
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc libncurses-dev openssl libssl-dev

      # Step 3: Download and build Emacs 29.3
      - name: Build Emacs
        run: |
          wget https://ftp.gnu.org/gnu/emacs/emacs-29.3.tar.gz
          tar -xzf emacs-29.3.tar.gz
          cd emacs-29.3
          ./configure
          make -j
          sudo make install

      # Step 4: Cache the ELPA directory to speed up future runs
      - name: Cache ELPA packages
        uses: actions/cache@v4
        with:
          path: ~/.emacs.d/elpa
          key: elpa-${{ runner.os }}-29.3-${{ hashFiles('**/*.el') }}
          restore-keys: |
            elpa-${{ runner.os }}-29.3-

      # Step 5: Install deps & byte-compile
      - name: Install deps & byte-compile
        run: |
          set -euo pipefail
          emacs --batch -Q -l ci-setup.el -f batch-byte-compile \
            chromadb.el \
            drip.el
