name: Emacs package CI

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    name: byte-compile on ${{ matrix.emacs }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        emacs: ['27.2', '28.2', '29.3', 'snapshot']

    steps:
      # Step 1: Check out the source code
      - uses: actions/checkout@v4

      # Step 2: Install dependencies for building Emacs
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc libncurses-dev

      # Step 3: Download and build the requested Emacs version
      - name: Build Emacs
        run: |
          wget https://ftp.gnu.org/gnu/emacs/emacs-${{ matrix.emacs }}.tar.gz
          tar -xzf emacs-${{ matrix.emacs }}.tar.gz
          cd emacs-${{ matrix.emacs }}
          ./configure --with-gnutls=ifavailable
          make -j
          sudo make install

      # Step 4: Cache the ELPA directory to speed up future runs
      - name: Cache ELPA packages
        uses: actions/cache@v4
        with:
          path: ~/.emacs.d/elpa
          key: elpa-${{ runner.os }}-${{ matrix.emacs }}-${{ hashFiles('**/*.el') }}
          restore-keys: |
            elpa-${{ runner.os }}-${{ matrix.emacs }}-

      # Step 5: Install deps & byte-compile
      - name: Install deps & byte-compile
        run: |
          set -euo pipefail
          emacs --batch -Q -l ci-setup.el -f batch-byte-compile \
            chromadb.el \
            drip.el
